
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nahin
 */
public class FromBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form FromBiblioteca
     */
    public FromBiblioteca() {
        initComponents();
        try {
           LlenarCBX(CBXSupervisor);
                       setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(FromBiblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreBiblioteca = new javax.swing.JTextField();
        IdBibliJLabel = new javax.swing.JLabel();
        DireccionBiblioteca = new javax.swing.JTextField();
        DireccionBibliotecaJLabel = new javax.swing.JLabel();
        EliminarBJBUTTON = new javax.swing.JButton();
        ConsultBJBUTTON = new javax.swing.JButton();
        UpdtBiblioJBUTTON = new javax.swing.JButton();
        AddBiblioJBUTTON = new javax.swing.JButton();
        CBXSupervisor = new javax.swing.JComboBox<Supervisor>();
        IdBibliotecaJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        LabelIdBiblioteca = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        ClearJBUTTON1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Biblioteca");

        NombreBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreBibliotecaActionPerformed(evt);
            }
        });

        IdBibliJLabel.setText("Nombre Biblioteca:");

        DireccionBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionBibliotecaActionPerformed(evt);
            }
        });

        DireccionBibliotecaJLabel.setText("Direccion Biblioteca:");

        EliminarBJBUTTON.setText("DELETE");
        EliminarBJBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBJBUTTONActionPerformed(evt);
            }
        });

        ConsultBJBUTTON.setText("CONSULT");
        ConsultBJBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultBJBUTTONActionPerformed(evt);
            }
        });

        UpdtBiblioJBUTTON.setText("UPDATE");
        UpdtBiblioJBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdtBiblioJBUTTONActionPerformed(evt);
            }
        });

        AddBiblioJBUTTON.setText("ADD");
        AddBiblioJBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBiblioJBUTTONActionPerformed(evt);
            }
        });

        CBXSupervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBXSupervisorMouseClicked(evt);
            }
        });
        CBXSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXSupervisorActionPerformed(evt);
            }
        });

        IdBibliotecaJLabel.setText("Supervisor:");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdBiblioteca", "Nombre", "Direccion", "Supervisor"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setText("IdBiblioteca:");

        LabelIdBiblioteca.setText(" ");

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        ClearJBUTTON1.setText("Clear");
        ClearJBUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearJBUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelIdBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(IdBibliJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DireccionBibliotecaJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DireccionBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IdBibliotecaJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBXSupervisor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConsultBJBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarBJBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdtBiblioJBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddBiblioJBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClearJBUTTON1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LabelIdBiblioteca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdBibliJLabel)
                            .addComponent(NombreBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionBibliotecaJLabel)
                            .addComponent(DireccionBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdBibliotecaJLabel)
                            .addComponent(CBXSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBiblioJBUTTON)
                    .addComponent(UpdtBiblioJBUTTON)
                    .addComponent(EliminarBJBUTTON)
                    .addComponent(ConsultBJBUTTON)
                    .addComponent(ClearJBUTTON1)
                    .addComponent(Menu))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreBibliotecaActionPerformed

    private void DireccionBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionBibliotecaActionPerformed

    private void UpdtBiblioJBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdtBiblioJBUTTONActionPerformed
        try {
            // TODO add your handling code here:

            Biblioteca B = new Biblioteca();
            B.setDireccion(DireccionBiblioteca.getText());
            B.setNombre(NombreBiblioteca.getText());
            B.setIdSupervisor(CBXSupervisor.getSelectedIndex() + 1);
            B.setIdBiblioteca(Integer.parseInt(LabelIdBiblioteca.getText()));
            B.Actualizar_Biblioteca();
            this.mostrar(Tabla, "select * from biblioteca");
        } catch (Exception ex) {
            Logger.getLogger(FromBiblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdtBiblioJBUTTONActionPerformed

    private void CBXSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXSupervisorActionPerformed

    private void CBXSupervisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBXSupervisorMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            FormSupervisor FS = new FormSupervisor();
            FS.setVisible(true);
        }
    }//GEN-LAST:event_CBXSupervisorMouseClicked

    private void AddBiblioJBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBiblioJBUTTONActionPerformed
        try {
            Supervisor S= (Supervisor) CBXSupervisor.getSelectedItem();
            Biblioteca B = new Biblioteca();
            B.setDireccion(DireccionBiblioteca.getText());
            B.setNombre(NombreBiblioteca.getText());
            B.setIdSupervisor(S.getIdSupersvisor());
            B.Insertar_Biblioteca();
            this.mostrar(Tabla, "select * from biblioteca");

        } catch (Exception ex) {
            Logger.getLogger(FromBiblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddBiblioJBUTTONActionPerformed

    private void EliminarBJBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBJBUTTONActionPerformed
        try {
            // TODO add your handling code here:
            Biblioteca B = new Biblioteca();
            B.setIdBiblioteca(Integer.parseInt(LabelIdBiblioteca.getText()));
            B.Eliminar_Biblioteca();
            this.mostrar(Tabla, "select * from biblioteca");
        } catch (Exception ex) {
            Logger.getLogger(FromBiblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EliminarBJBUTTONActionPerformed

    private void ConsultBJBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultBJBUTTONActionPerformed

        this.mostrar(Tabla, "select * from biblioteca");        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultBJBUTTONActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        MouseClick();
    }//GEN-LAST:event_TablaMouseClicked

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        FormPrueba P = new FormPrueba();
        P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void ClearJBUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearJBUTTON1ActionPerformed
        // TODO add your handling code here:
       LabelIdBiblioteca.setText("");
       NombreBiblioteca.setText("");
       DireccionBiblioteca.setText("");
    }//GEN-LAST:event_ClearJBUTTON1ActionPerformed

    private void MouseClick() {
        int fila = Tabla.getSelectedRow();
        LabelIdBiblioteca.setText(Tabla.getModel().getValueAt(fila, 0).toString());
        NombreBiblioteca.setText(Tabla.getModel().getValueAt(fila, 3).toString());
        DireccionBiblioteca.setText(Tabla.getModel().getValueAt(fila, 1).toString());
        CBXSupervisor.setSelectedIndex(Integer.parseInt(Tabla.getModel().getValueAt(fila, 2).toString()) - 1);
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            Clientes cb = new Clientes();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }
public void LlenarCBX(JComboBox AA) throws Exception {
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        AA.setModel(modelo);
        Supervisor S = new Supervisor();
        ArrayList<Supervisor> ListaS = S.SupervisorVista();
        CBXSupervisor.removeAllItems();
        for (int i = 0; i < ListaS.size(); i++) {
            modelo.addElement(ListaS.get(i));
            
        }
     AA.setModel(modelo);
    }
//public void LlenarCBX(JComboBox AA) throws Exception {
//        DefaultComboBoxModel BB= new DefaultComboBoxModel();
//        Supervisor S = new Supervisor();
//        ArrayList<Supervisor> ListaS = S.SupervisorVista();
//        CBXSupervisor.removeAllItems();
//        for (int i = 0; i < ListaS.size(); i++) {
//            CBXSupervisor.addItem(ListaS.get(i));
//            
//        }
//     
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBiblioJBUTTON;
    private javax.swing.JComboBox<Supervisor> CBXSupervisor;
    private javax.swing.JButton ClearJBUTTON1;
    private javax.swing.JButton ConsultBJBUTTON;
    private javax.swing.JTextField DireccionBiblioteca;
    private javax.swing.JLabel DireccionBibliotecaJLabel;
    private javax.swing.JButton EliminarBJBUTTON;
    private javax.swing.JLabel IdBibliJLabel;
    private javax.swing.JLabel IdBibliotecaJLabel;
    private javax.swing.JLabel LabelIdBiblioteca;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField NombreBiblioteca;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton UpdtBiblioJBUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
